### ISSUE TITLE
Angular JS file templates doesn't appear on Add New Item window for Apache Cordova projects

### ISSUE THREAD

**Issue by fals** [ligershark/side-waffle#227] opened 2015-02-19 16:05 UTC
I juste notice that any of those templates for Angular JS doesn't show on the Add New Item window at Visual Studio 2013. But those show up for any web projects. Given that hybrids apps are using Angular JS side by side with Cordova, that this Item templates stay avaible at the JavaScript Project category as well.

**Comment by sayedihashimi** [comment] 2015-02-19 20:44
Looks like it's working for me with the latest from [sidewaffle.com](http://sidewaffle.com). What issues are you having?

![cordova](https://cloud.githubusercontent.com/assets/1283154/6275569/0312fb98-b835-11e4-9909-f4ff7e26caae.png)

**Comment by fals** [comment] 2015-02-20 15:51
Well, i can't see this when I click Add New Item. I already did a full reinstall for Side Waffle and still the same. The same issue with Visual Studio 2015, which is a full new installation.

**Comment by sayedihashimi** [comment] 2015-02-20 16:02
Does it work otherwise? You're not giving enough info so that we can help. What's the steps your following?

**Comment by fals** [comment] 2015-02-20 16:25
Yes, it does, when I'm have a Web Application selected every template shows as expected.

**Comment by sayedihashimi** [comment] 2015-02-20 17:39
@fals you haven't given enough info for us to help you. The following will be helpful.

 - Specific steps to follow to reproduce (including language is it C# or VB)
 - Machine config
 - Anything else that may be different from your setup and mine

**Comment by RandomlyKnighted** [comment] 2015-02-28 05:04
@sayedihashimi I'm able to reproduce this bug as well. I created a basic Cordova JavaScript project then when I went to the Add New Item dialog the only thing that showed up was the generic JavaScript item templates.

![cordova_app_problem](https://cloud.githubusercontent.com/assets/2483249/6424940/ab976fec-bed4-11e4-8cca-8b26c8d24b84.PNG)

I'm using the latest version of SideWaffle (1.15) from the website.

**Comment by sayedihashimi** [comment] 2015-02-28 06:28
How about other project types like a standard AspNet web app project? Is it specific to Cordova?

**Comment by RandomlyKnighted** [comment] 2015-02-28 07:14
Yes, it seems to be specific to Cordova.

**Comment by fals** [comment] 2015-03-02 19:55
@sayedihashimi and @RandomlyKnighted That's exactly what I'm talking about.

**Comment by sayedihashimi** [comment] 2015-03-08 22:56
Cordova is implemented in Visual Studio as a "Project Type/Project System". Each project system get's to control how templates are displayed.

The method that SideWaffle uses to enable templates across project types is that we add ``` <AppliesTo>ABC | (!ABC)</AppliesTo>``` to the .vstemplate file (for example [see here](https://github.com/ligershark/side-waffle/blob/master/TemplatePack/ItemTemplates/Web/JavaScript/AngularJs/Controller%20As/_Definitions/CSharp.vstemplate#L10)). By using that expression it should be shown for all project types. However project type/system owners can opt out of this. It seems like Cordova has opted out.

The only way that SideWaffle could support Cordova would be to author item templates specifically for Cordova. That would mean:
 1. Changes to TemplateBuilder to support something like cordova.vstemplate
 1. Update all existing item templates in SideWaffle to include cordova.vstemplate
 1. When the SideWaffle vsix is created all item templates will be duplicated across C# and Cordova so the vsix size would basically double.

I'm especially concerned with the increase in the .vsix size. it's already at about 10mb, adding this would cause it to get closer to 20mb.

I would take it up with the Cordova team. I would recommend adding a user voice item to http://visualstudio.uservoice.com/ stating that SideWaffle templates do not show up. You can point to this comment for the technical details why not.

Closing this issue as there is no further action in SideWaffle/TemplateBuilder.

**Closed by sayedihashimi** 2015-03-08 22:56 UTC
