### ISSUE TITLE
Multi project template - additional folder in generated structure - impact on nuget

### ISSUE THREAD

**Issue by gaspode44** [ligershark/side-waffle#169] opened 2014-08-21 08:19 UTC
Hi,

I'm looking for some guidance on how best to incorporate nugget packages with a multi project solution template - I've followed the guidance on nugget.org to include my packages in the vsix in a packages folder located in the root of the template - such that when it gets installed its at the same level as the "Output" folder (under the version folder eg 1.0)

However in my case I'm attempting to build a multi project template and when I create a new project based on this template I get an additional folder (same name as the project name entered by the user) under which the actual projects get created

Solution folder
- foo.sln
- foo.suo
- foo <- new solution folder which is unwanted
---project A
---project B

This breaks the projects as any assembly references introduced by  nugget package are now incorrect

Is there way to avoid the creation of this additional folder ?

Richard

**Comment by sayedihashimi** [comment] 2015-04-06 17:18
Looks like a dupe of #237. There are details about how to work around it with a custom wizard there. I'll close this but if it's different then please re-open with details.

**Closed by sayedihashimi** 2015-04-06 17:18 UTC
