### ISSUE TITLE
Cannot generate scaffolded item in Visual studio 2015

### ISSUE THREAD

**Issue by AudeR** [ligershark/side-waffle#384] opened 2016-07-07 23:57 UTC
The following error occurs after the ASP.net scaffolding T4 files are in the project while attempting to add a new scaffolding item in Visual studio 2015 community MVC project.

![image](https://cloud.githubusercontent.com/assets/20346730/16673513/cb4d730c-447c-11e6-8814-ef9404a81524.png)

This error does not occur if the the T4 files have not been added to the project.

**Comment by sayedihashimi** [comment] 2016-07-08 00:26
@AudeR are you using Visual Studio Community Edition?

**Comment by AudeR** [comment] 2016-07-08 13:47
Yes

**Comment by sayedihashimi** [comment] 2016-07-08 16:36
@AudeR ok thanks. This is a duplicate of https://github.com/ligershark/side-waffle/issues/330 which the underlying issue is actually a bug in VS Community Editon. I've opened https://github.com/aspnet/Tooling/issues/585 to track that. There hasn't been any update there yet, but I'm working with my team at Microsoft to start an investigation there.

Closing this.

**Closed by sayedihashimi** 2016-07-08 16:36 UTC

**Comment by AudeR** [comment] 2016-07-08 20:02
Thank  you for the update and following-up. I did notice issue #330 and posted on it as well, however I realized that # 330 is closed. So this is why I opened this new ticket.

**Comment by sayedihashimi** [comment] 2016-07-08 20:20
I closed the other ticket because there is nothing the SideWaffle can do to resolve it. Are you saying we should leave the other issue open for discoverability?

**Comment by AudeR** [comment] 2016-07-08 20:55
Yes. Thank you for following-up with Microsoft.
