### ISSUE TITLE
Not installing on VS2015 RTM on Win 10

### ISSUE THREAD

**Issue by andre-artus** [ligershark/side-waffle#302] opened 2015-09-03 21:19 UTC
I had SideWaffle previously installed but some time after upgrading to Win 10 it showed an update notification in VS (2015, Professional). I attempted the update, but it did nothing. I decided to download and install, but it does nothing. I tried installing from within VS Extensions and Updates, but all it does is open the browser (Edge) and start a download. Every other extension (bar one, "Code Contracts for .NET") that I've installed previously, and since, just shows a license window and starts downloading and installing if you agree.

I've downloaded the "templatepack.vsix" numerous times thinking that it may be corrupt (md5sum is 8676ce517380f0c8ce759963496a1132 for all of them). And I have tried installing it by running VSIXInstaller. I've even done a "devenv /ResetSettings". Only thing I have not tried is a reinstall (it takes too long).

**Comment by andre-artus** [comment] 2015-09-03 21:25
I forgot to add that I uninstalled the previous installation when it failed to update, in the hope that a "fresh" install would take. It did not. It does not report an error. 

I have VS 2008 Professional, VS 2010 (probably from SQL management studio), and 2015 Prof.. I had 2013 Prof. installed before 2015 went RTW/RTM.

**Comment by sayedihashimi** [comment] 2015-09-03 21:38
@andre-artus are you saying that all third party extensions are not working for you our just SideWaffle?

**Comment by andre-artus** [comment] 2015-09-03 23:32
Others are installing, updating, and working. SideWaffle isn't.

**Comment by davemvp** [comment] 2015-09-04 10:09
I'm having the same issue with the Sidewaffle.vsix file. I have tried running VSIXInstaller from a command line and passing the templates.vsix file as an argument. There is no dialog, no nothing. I found other vsixinstaller logs in my appData folder but nothing for SideWaffle.

I previously had Visual Studio 2013 on my machine before upgrading to Windows 10. I uninstalled Visual Studio 2013, upgraded to Windows 10, and then installed Visual Studio 2015. Other extensions are installing and updating fine.

**Comment by davemvp** [comment] 2015-09-04 11:28
This may be a bigger problem with Visual Studio. The following issue seems very similar. https://github.com/github/VisualStudio/issues/28. I went looking in event viewer and found the exact same error messages as reported in the link above. Unfortunately I started looking at the event logs while I am repairing Visual Studio. As Chaim1221 indicates the extension manager within Visual Studio seems to work fine. I'll verify if I run the vsixinstaller as admin if it installs.

**Comment by andre-artus** [comment] 2015-09-04 12:34
From event viewer:
Problem signature:
P1: VSIXInstaller.exe
P2: 14.0.23107.0
P3: 559b7195
P4: mscorlib
P5: 4.6.96.0
P6: 55b96801
P7: 157e
P8: 12e
P9: System.UnauthorizedAccess
P10: 

Attached files:
C:\Users\Andre Artus\AppData\Local\Temp\WER1C14.tmp.WERInternalMetadata.xml

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_VSIXInstaller.ex_16b6a26652c63f7909bdeedb6fb447245df67a1_015e2318_0ab72125

Analysis symbol: 
Rechecking for solution: 0
Report ID: ec3e30b8-a6d4-4fab-a37c-58b6cf147a73
Report Status: 0
Hashed bucket: 004a03714de54520fe7923f537c088c3

**Comment by andre-artus** [comment] 2015-09-04 12:38
From Report.wer:

Version=1
EventType=CLR20r3
EventTime=130858435360598081
ReportType=2
Consent=1
UploadTime=130858435361298083
ReportIdentifier=f92bc20a-5300-11e5-8337-000272d46000
IntegratorReportIdentifier=ec3e30b8-a6d4-4fab-a37c-58b6cf147a73
WOW64=1
NsAppName=VSIXInstaller.exe
Response.BucketId=004a03714de54520fe7923f537c088c3
Response.BucketTable=5
Response.LegacyBucketId=128890715620
Response.type=4
Sig[0].Name=Problem Signature 01
Sig[0].Value=VSIXInstaller.exe
Sig[1].Name=Problem Signature 02
Sig[1].Value=14.0.23107.0
Sig[2].Name=Problem Signature 03
Sig[2].Value=559b7195
Sig[3].Name=Problem Signature 04
Sig[3].Value=mscorlib
Sig[4].Name=Problem Signature 05
Sig[4].Value=4.6.96.0
Sig[5].Name=Problem Signature 06
Sig[5].Value=55b96801
Sig[6].Name=Problem Signature 07
Sig[6].Value=157e
Sig[7].Name=Problem Signature 08
Sig[7].Value=12e
Sig[8].Name=Problem Signature 09
Sig[8].Value=System.UnauthorizedAccess
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=10.0.10240.2.0.0.256.48
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=7177
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=bdcb
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=bdcb33e65a9843796b7ec31cc25bda3b
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=689d
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=689d12abf00dd47c453b5e1a156c0fa3
UI[2]=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\VSIXInstaller.exe
UI[3]=Microsoft VSIX Installer has stopped working
UI[4]=Windows can check online for a solution to the problem.
UI[5]=Check online for a solution and close the program
UI[6]=Check online for a solution later and close the program
UI[7]=Close the program
LoadedModule[0]=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\VSIXInstaller.exe
LoadedModule[1]=C:\WINDOWS\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\WINDOWS\SYSTEM32\MSCOREE.DLL
LoadedModule[3]=C:\WINDOWS\SYSTEM32\KERNEL32.dll
LoadedModule[4]=C:\WINDOWS\SYSTEM32\KERNELBASE.dll
LoadedModule[5]=C:\WINDOWS\SYSTEM32\ADVAPI32.dll
LoadedModule[6]=C:\WINDOWS\SYSTEM32\msvcrt.dll
LoadedModule[7]=C:\WINDOWS\SYSTEM32\sechost.dll
LoadedModule[8]=C:\WINDOWS\SYSTEM32\RPCRT4.dll
LoadedModule[9]=C:\WINDOWS\SYSTEM32\SspiCli.dll
LoadedModule[10]=C:\WINDOWS\SYSTEM32\CRYPTBASE.dll
LoadedModule[11]=C:\WINDOWS\SYSTEM32\bcryptPrimitives.dll
LoadedModule[12]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscoreei.dll
LoadedModule[13]=C:\WINDOWS\SYSTEM32\SHLWAPI.dll
LoadedModule[14]=C:\WINDOWS\SYSTEM32\combase.dll
LoadedModule[15]=C:\WINDOWS\SYSTEM32\GDI32.dll
LoadedModule[16]=C:\WINDOWS\SYSTEM32\USER32.dll
LoadedModule[17]=C:\WINDOWS\SYSTEM32\IMM32.DLL
LoadedModule[18]=C:\WINDOWS\SYSTEM32\MSCTF.dll
LoadedModule[19]=C:\WINDOWS\SYSTEM32\kernel.appcore.dll
LoadedModule[20]=C:\WINDOWS\SYSTEM32\VERSION.dll
LoadedModule[21]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
LoadedModule[22]=C:\WINDOWS\SYSTEM32\MSVCR120_CLR0400.dll
LoadedModule[23]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\mscorlib\739821138ef3780d29566f16c4ec3836\mscorlib.ni.dll
LoadedModule[24]=C:\WINDOWS\SYSTEM32\ole32.dll
LoadedModule[25]=C:\WINDOWS\system32\uxtheme.dll
LoadedModule[26]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System\ca6efbdfe42568e069a7e2f1a869de59\System.ni.dll
LoadedModule[27]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\WindowsBase\a60407f3be68f78c08f92470170d47d5\WindowsBase.ni.dll
LoadedModule[28]=C:\WINDOWS\SYSTEM32\CRYPTSP.dll
LoadedModule[29]=C:\WINDOWS\SYSTEM32\bcrypt.dll
LoadedModule[30]=C:\WINDOWS\system32\rsaenh.dll
LoadedModule[31]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\PresentationCore\ffaa9902a9d7148d8350a479b37aa3c6\PresentationCore.ni.dll
LoadedModule[32]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\Presentatio5ae0f00f#\7b5a037b8047ae7620a561783e9b0e3d\PresentationFramework.ni.dll
LoadedModule[33]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System.Xaml\5403149bb59b86425b507f62a345576a\System.Xaml.ni.dll
LoadedModule[34]=C:\WINDOWS\SYSTEM32\dwrite.dll
LoadedModule[35]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\WPF\wpfgfx_v0400.dll
LoadedModule[36]=C:\WINDOWS\SYSTEM32\OLEAUT32.dll
LoadedModule[37]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\WPF\PresentationNative_v0400.dll
LoadedModule[38]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\clrjit.dll
LoadedModule[39]=C:\WINDOWS\system32\dwmapi.dll
LoadedModule[40]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System.Core\c443a8daf03f55a14ffe24ec583664da\System.Core.ni.dll
LoadedModule[41]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\Microsoft.Vd5d72abf#\bfa53fd61c5b4365d1156b8fc51c24e4\Microsoft.VisualStudio.ExtensionManager.ni.dll
LoadedModule[42]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\Microsoft.Vf617de63#\5498e1b3db463acd0b320247f78adc99\Microsoft.VisualStudio.ExtensionManager.Implementation.ni.dll
LoadedModule[43]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\diasymreader.dll
State[0].Key=Transport.DoneStage1
State[0].Value=1
FriendlyEventName=Stopped working
ConsentKey=CLR20r3
AppName=Microsoft VSIX Installer
AppPath=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\VSIXInstaller.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=0D32BB2C43ADEA4FFF7F6BB4A9C364D6

**Comment by andre-artus** [comment] 2015-09-04 12:42
More from EV:

Application: VSIXInstaller.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.UnauthorizedAccessException
Stack:
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.FileStream.Init(System.String, System.IO.FileMode, System.IO.FileAccess, Int32, Boolean, System.IO.FileShare, Int32, System.IO.FileOptions, SECURITY_ATTRIBUTES, System.String, Boolean, Boolean, Boolean)
   at System.IO.FileStream..ctor(System.String, System.IO.FileMode, System.IO.FileAccess)
   at VSIXInstaller.Logger..ctor(System.String)
   at VSIXInstaller.Logger.InitializeLogger(System.String)
   at VSIXInstaller.Logger.get_Instance()
   at VSIXInstaller.Logger.WriteLine(System.String)
   at VSIXInstaller.App.InitializationExceptionHandler(System.Exception)
   at VSIXInstaller.App.OnStartup(System.Windows.StartupEventArgs)
   at System.Windows.Application.<_ctor>b__0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at VSIXInstaller.App.Main()

and


Faulting application name: VSIXInstaller.exe, version: 14.0.23107.0, time stamp: 0x559b7195
Faulting module name: KERNELBASE.dll, version: 10.0.10240.16384, time stamp: 0x559f3b2a
Exception code: 0xe0434352
Fault offset: 0x000b3e28
Faulting process ID: 0x372c
Faulting application start time: 0x01d0e70dbb394b21
Faulting application path: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\VSIXInstaller.exe
Faulting module path: C:\WINDOWS\SYSTEM32\KERNELBASE.dll
Report ID: ec3e30b8-a6d4-4fab-a37c-58b6cf147a73
Faulting package full name: 
Faulting package-relative application ID:

**Comment by sayedihashimi** [comment] 2015-09-04 16:54
Also from comments at https://github.com/github/VisualStudio/issues/28 it sounds like you should try to run the .vsix as an Administrator. To do that you can open an admin command prompt and execute the .vsix.

If that doesn't work, can you try out https://ci.appveyor.com/api/buildjobs/64k2b2vgnletq109/artifacts/TemplatePack.vsix and see if that installs correctly? We recently merged some significant changes and I'd like to see if this previous build works for you or not.

**Comment by andre-artus** [comment] 2015-09-04 17:45
I first tried out the version of templatepack.vsix linked above as a normal restricted privilege user. Same errors.

Then I tried to install the latest vsix (the one that was not working previously) using admin privileges, and that worked.

**Comment by sayedihashimi** [comment] 2015-09-04 18:43
@andre-artus OK so this does look like an issue with VS where admin privileges are required. I've already commented on https://github.com/github/VisualStudio/issues/28 so let's see if there is any update there.

**Comment by andre-artus** [comment] 2015-09-04 21:24
Thanks, Sayed, for helping mew to resolve my immediate issues. It would
probably be worth a note on the website/github until this issue gets a more
permanent solution.

**Comment by davemvp** [comment] 2015-09-04 22:36
Another thing I noticed that was different between the two machines I was testing with was that one had IIS installed (the one requiring to run as admin) and the other didn't. Maybe IIS triggers the need for elevated privileges?

**Comment by codymullins** [comment] 2015-09-06 20:34
@davemvp I don't have IIS installed and still had the error

**Comment by RandomlyKnighted** [comment] 2015-09-14 02:51
Since we have come to the conclusion that the issue is with Visual Studio itself I'm going to go ahead and close this.

**Closed by RandomlyKnighted** 2015-09-14 02:51 UTC
